### GET request to example server
POST http://lb-9b5d382a.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Zaylee Tinomudaishe Machinya",
  "email": "tinoZr@gmail.com",
  "address": "4311 57th Ave apt 7",
  "dateOfBirth": "2021-06-13",
  "registeredDate": "2025-04-16"
}

###