### GET request to example server
POST http://lb-6c326952.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Tinomudaishe",
  "email": "tinomudaishe@gmail.com",
  "address": "4311 57th Ave aapt 71th",
  "dateOfBirth": "2021-06-13",
  "registeredDate": "2025-04-04"
}

###