### Update an existing entity
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "Isabella Walker",
  "address": "789 Willow St, Springfield 123",
  "email": "isabella3.walker@example.com",
  "dateOfBirth": "1987-10-17"
}

###